server {
    listen 80;
    server_name localhost;

    # La ruta donde Docker copia tu carpeta "public"
    root /usr/share/nginx/html;
    index index.html;

    # Regla principal para cargar la página
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché automático para tus imágenes, CSS y JS (Hace la web más rápida)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}